FarmaciaBD/Models/Medicamento.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FarmaciaBD.Models
{
    public class Medicamento
    {
        [Required(ErrorMessage = "Campo obrigatório")]
        public int Codigo { get; set; }

        [Required(ErrorMessage = "Campo obrigatório")]
        public string Laboratorio { get; set; }

        [Required(ErrorMessage = "Campo obrigatório")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "Campo obrigatório")]
        public string Composicao { get; set; }

        [Required(ErrorMessage = "Campo obrigatório")]
        public string Tarja { get; set; }

        [Required(ErrorMessage = "Campo obrigatório")]
        public string Tipo { get; set; }

        [Required(ErrorMessage = "Campo obrigatório")]
        public int Produto_codigo_de_barras { get; set; }
    }
}

FarmaciaBD/Controllers/FuncionarioController.cs
using FarmaciaBD.Models;
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
namespace FarmaciaBD.Controllers
{
    public class FuncionarioController : Controller
    {
        
        public IActionResult Index()
        {

            List<Funcionario> funcionarios = new List<Funcionario>();

            
            using (MySqlConnection conexao = new MySqlConnection("server=localhost;user=root;database=farmacia;port=3306;password=gatosloucos"))
            {

                conexao.Open();
                MySqlCommand comando = new MySqlCommand("select *from funcionario;", conexao);
                MySqlDataReader reader = comando.ExecuteReader();

                while (reader.Read())
                {
                    // extract your data
                    Funcionario funcionario = new Funcionario
                    {
                        Matricula = Convert.ToInt32(reader["matricula"]),
                        Nascimento =reader["nascimento"].ToString(),
                        Nome = reader["nome"].ToString(),
                        Cargo = reader["cargo"].ToString(),
                        Sexo = reader["sexo"].ToString(),
                        Salario = reader["salario"].ToString(),
                        Loja_numero = Convert.ToInt32(reader["loja_numero"])


                       

                };

                    funcionarios.Add(funcionario);
                }
                reader.Close();

            }
            return View(funcionarios);
        }

        [HttpGet]
        public IActionResult Inserir()
        {

            return View(new Funcionario());
        }

        [HttpPost]
        public IActionResult Inserir([FromForm] Funcionario funcionario)
        {
            try {
                using (MySqlConnection conexao = new MySqlConnection("server=localhost;user=root;database=farmacia;port=3306;password=gatosloucos"))
                {
                    conexao.Open();
                    MySqlCommand comando = new MySqlCommand("insert into funcionario(nascimento, nome, cargo, sexo, salario, loja_Numero) values('" + funcionario.Nascimento + "','" + funcionario.Nome + "','" + funcionario.Cargo + "','" + funcionario.Sexo + "','" + funcionario.Salario + "'," + funcionario.Loja_numero + ");", conexao);
                    
                    comando.ExecuteNonQuery();
                    conexao.Close();
                    TempData["Mensagem"] = "O funcionário foi cadastrado com sucesso!";
                    
                }
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                    TempData["Exception"] = "Você digitou uma loja existente? Verifique também o formato da data";
            }
                 
            return View("Inserir", funcionario);
        }

        [HttpGet, ActionName("Deletar")]
        public IActionResult Deletar(int Numero)
        {
            Console.WriteLine(Numero);
            using (MySqlConnection conexao = new MySqlConnection("server=localhost;user=root;database=farmacia;port=3306;password=gatosloucos"))
            {
                conexao.Open();
                MySqlCommand comando = new MySqlCommand("DELETE FROM funcionario WHERE matricula = '" + Numero + "'", conexao);

                comando.ExecuteNonQuery();

                TempData["Mensagem"] = "O funcionário'" + Numero + "' foi excluído com sucesso!";
                conexao.Close();
            }
            return RedirectToAction("Index");
        }


        [HttpGet, ActionName("Update")]
        public IActionResult Update(int Numero)
        {
            
            List<Funcionario> funcionarios = new List<Funcionario>();
            using (MySqlConnection conexao = new MySqlConnection("server=localhost;user=root;database=farmacia;port=3306;password=gatosloucos"))
            {
                conexao.Open();
                MySqlCommand comando = new MySqlCommand("SELECT *FROM funcionario " +
                    "WHERE matricula ='" + Numero + "'", conexao);
                MySqlDataReader reader = comando.ExecuteReader();

                while (reader.Read())
                {
                    // extract your data
                    Funcionario funcionario = new Funcionario
                    {
                        Matricula = Convert.ToInt32(reader["matricula"]),
                        Nascimento = reader["nascimento"].ToString(),
                        Nome = reader["nome"].ToString(),
                        Cargo = reader["cargo"].ToString(),
                        Sexo = reader["sexo"].ToString(),
                        Salario = reader["salario"].ToString(),
                        Loja_numero = Convert.ToInt32(reader["loja_numero"])
                        
                    };
                    funcionarios.Add(funcionario);

                }
                    reader.Close();

            }
            return View("Atualizar", funcionarios);
        }

        [HttpPost]
        public IActionResult Update([FromForm] Funcionario funcionario)
        {
            try
            {
                /*if (ModelState.IsValid)
                {*/
                    using (MySqlConnection conexao = new MySqlConnection("server=localhost;user=root;database=farmacia;port=3306;password=gatosloucos"))
                    {
                        conexao.Open();
                        MySqlCommand comando = new MySqlCommand(
                            "Update funcionario set nascimento='" + funcionario.Nascimento + "', nome='" + funcionario.Nome + "', cargo= '" + funcionario.Cargo + "', sexo='" + funcionario.Sexo + "', salario='" + funcionario.Salario + "',loja_numero='" + funcionario.Loja_numero + "' WHERE matricula=" + funcionario.Matricula + "", conexao);

                        comando.ExecuteNonQuery();

                        TempData["Mensagem"] = "O funcionário" + funcionario.Matricula + "' foi atualizado com sucesso!";
                        conexao.Close();
                        return RedirectToAction("Index");
                    }
                
            }
            
            catch(Exception)
            {
                TempData["Exception"] = "ERRO. Verifique se tentou cadastrar um número de loja existente";
                
            }
            
            return RedirectToAction("Index");
        }
         
    }
}

FarmaciaBD/Controllers/MedicamentoController.cs
using FarmaciaBD.Models;
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FarmaciaBD.Controllers
{
    public class MedicamentoController : Controller
    {

        public IActionResult Index()
        {

            List<Medicamento> medicamentos = new List<Medicamento>();


            using (MySqlConnection conexao = new MySqlConnection("server=localhost;user=root;database=farmacia;port=3306;password=gatosloucos"))
            {

                conexao.Open();
                MySqlCommand comando = new MySqlCommand("select *from medicamento;", conexao);
                MySqlDataReader reader = comando.ExecuteReader();

                while (reader.Read())
                {
                    // extract your data
                    Medicamento medicamento = new Medicamento
                    {
                        Codigo = Convert.ToInt32(reader["codigo"]),
                        Laboratorio = reader["laboratorio"].ToString(),
                        Nome = reader["nome"].ToString(),
                        Composicao = reader["composicao"].ToString(),
                        Tarja = reader["tarja"].ToString(),
                        Tipo = reader["tipo"].ToString(),
                        Produto_codigo_de_barras = Convert.ToInt32(reader["produto_codigo_de_barras"])

                };

                    medicamentos.Add(medicamento);
                }
                reader.Close();

            }
            return View(medicamentos);
        }

        [HttpGet]
        public IActionResult Inserir()
        {

            return View(new Medicamento());
        }

        [HttpPost]
        public IActionResult Inserir([FromForm] Medicamento medicamento)
        {
            try
            {
                using (MySqlConnection conexao = new MySqlConnection("server=localhost;user=root;database=farmacia;port=3306;password=gatosloucos"))
                {
                    conexao.Open();
                    MySqlCommand comando = new MySqlCommand("insert into medicamento(laboratorio, nome, composicao, tarja, tipo, produto_codigo_de_barras) values('" + medicamento.Laboratorio + "','" + medicamento.Nome + "','" + medicamento.Composicao + "','" + medicamento.Tarja + "','" + medicamento.Tipo + "'," + medicamento.Produto_codigo_de_barras + ");", conexao);

                    comando.ExecuteNonQuery();
                    conexao.Close();
                    TempData["Mensagem"] = "O medicamento foi cadastrado com sucesso!";

                }
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                TempData["Exception"] = "Você digitou um codigo de produto existente? Não pode existir repetição de códigos no banco.";
            }

            return View("Inserir", medicamento);
        }

        [HttpGet, ActionName("Deletar")]
        public IActionResult Deletar(int Numero)
        {
            Console.WriteLine(Numero);
            using (MySqlConnection conexao = new MySqlConnection("server=localhost;user=root;database=farmacia;port=3306;password=gatosloucos"))
            {
                conexao.Open();
                MySqlCommand comando = new MySqlCommand("DELETE FROM medicamento WHERE codigo = '" + Numero + "'", conexao);

                comando.ExecuteNonQuery();

                TempData["Mensagem"] = "O medicamento '" + Numero + "' foi excluído com sucesso!";
                conexao.Close();
            }
            return RedirectToAction("Index");
        }


        [HttpGet, ActionName("Update")]
        public IActionResult Update(int Numero)
        {

            List<Medicamento> medicamentos = new List<Medicamento>();
            using (MySqlConnection conexao = new MySqlConnection("server=localhost;user=root;database=farmacia;port=3306;password=gatosloucos"))
            {
                conexao.Open();
                MySqlCommand comando = new MySqlCommand("SELECT *FROM medicamento " +
                    "WHERE codigo ='" + Numero + "'", conexao);
                MySqlDataReader reader = comando.ExecuteReader();

                while (reader.Read())
                {
                    // extract your data
                    Medicamento medicamento = new Medicamento
                    {
                        Codigo = Convert.ToInt32(reader["codigo"]),
                        Laboratorio = reader["laboratorio"].ToString(),
                        Nome = reader["nome"].ToString(),
                        Composicao = reader["composicao"].ToString(),
                        Tarja = reader["tarja"].ToString(),
                        Tipo = reader["tipo"].ToString(),
                        Produto_codigo_de_barras = Convert.ToInt32(reader["produto_codigo_de_barras"])

                    };
                    medicamentos.Add(medicamento);

                }
                reader.Close();

            }
            return View("Atualizar", medicamentos);
        }

        [HttpPost]
        public IActionResult Update([FromForm] Medicamento medicamento)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (MySqlConnection conexao = new MySqlConnection("server=localhost;user=root;database=farmacia;port=3306;password=gatosloucos"))
                    {
                        conexao.Open();
                        MySqlCommand comando = new MySqlCommand(
                            "Update medicamento set laboratorio='" + medicamento.Laboratorio + "', nome='" + medicamento.Nome + "', composicao= '" + medicamento.Composicao + "', tarja='" + medicamento.Tarja + "', tipo='" + medicamento.Tipo + "',produto_codigo_de_barras='" + medicamento.Produto_codigo_de_barras + "' WHERE Codigo=" + medicamento.Codigo + "", conexao);

                        comando.ExecuteNonQuery();

                        TempData["Mensagem"] = "O Medicamento " + medicamento.Codigo + " foi atualizado com sucesso!";
                        conexao.Close();
                    }
                    return RedirectToAction("Index");
                }
            }
            catch (Exception)
            {
                TempData["Exception"] = "Você digitou um produto existente? Verifique também se não já o cadastrou";
            }
            return RedirectToAction("Index");
        }
    }
}

FarmaciaBD/Views/Medicamento/Atualizar.cshtml
@model List<FarmaciaBD.Models.Medicamento>
@{ Layout = "_Layout";
    ViewBag.Title = "Funcionário";
}
@if (TempData["Exception"] != null) // para evitar mensagem de erro atoa
{
    <div class="alert alert-danger" role="alert">
        @TempData["Exception"]
    </div>
}
<br /> <br />
<h2 style="text-align: center">Atualizando Medicamento</h2>
@foreach (var medicamento in Model)
{
    <p>Código do Medicamento: @medicamento.Codigo</p>

    <form method="post">
        <input type="hidden" name="codigo" value="@medicamento.Codigo" />
        <div class="row g-3">
            <div class="col-12">
                <label for="nome" class="form-label">Nome</label>
                <input type="text" name="nome" class="form-control" value="@medicamento.Nome" id="nome">
                <a style="color:red">
                    @Html.ValidationMessage("nome")
                </a>
            </div>
            <div class="col-md-6">
                <label for="laboratorio" class="form-label">Laboratório</label>
                <input type="text" name="laboratorio" class="form-control" value="@medicamento.Laboratorio" id="laboratorio">

                <a style="color:red">
                    @Html.ValidationMessage("laboratorio")
                </a>
            </div>
            <div class="col-md-6">
                <label for="composicao" class="form-label">Composição</label>
                <input type="text" name="composicao" class="form-control" value="@medicamento.Composicao" id="composicao">

                <a style="color:red">
                    @Html.ValidationMessage("composicao")
                </a>
            </div>
            <div class="col-md-4">
                <label for="tarja" class="form-label">Tarja</label>
                <input type="text" name="tarja" class="form-control" value="@medicamento.Tarja" id="tarja">

                <a style="color:red">
                    @Html.ValidationMessage("tarja")
                </a>
            </div>
            <div class="col-md-4">
                <label for="tipo" class="form-label">Tipo</label>
                <input type="text" name="tipo" class="form-control" value="@medicamento.Tipo" id="tipo">

                <a style="color:red">
                    @Html.ValidationMessage("tipo")
                </a>
            </div>

            <div class="col-md-4">
                <label for="produto_codigo_de_barras" class="form-label">Código do Produto</label>
                <input type="text" name="produto_codigo_de_barras" class="form-control" value="@medicamento.Produto_codigo_de_barras" id="produto_codigo_de_barras">
                <a style="color:red">
                    @Html.ValidationMessage("produto_codigo_de_barras")
                </a>
            </div>

        </div>
        <button type="submit" class="btn btn-secondary">Salvar</button>
    </form>
}

FarmaciaBD/Views/Medicamento/Index.cshtml
@model List<FarmaciaBD.Models.Medicamento>
@{ Layout = "_Layout";
    ViewBag.Title = "Medicamento";
}
@if (TempData["Mensagem"] != null) // para evitar mensagem de erro atoa
{
    <div class="alert alert-success" role="alert">
        @TempData["Mensagem"]
    </div>
}
@if (TempData["Exception"] != null) // para evitar mensagem de erro atoa
{
    <div class="alert alert-danger" role="alert">
        @TempData["Exception"]
    </div>
}
<br />
<br />
<h2 style="text-align: center">Medicamentos</h2>
@*<a>@Html.ActionLink("Cadastrar novo funcionário", "Inserir", "Funcionario")</a>*@
<a href="/medicamento/inserir" class="btn btn-secondary"> Cadastrar novo medicamento </a>
<!---->
<table class="table table-bordered">
    <thead class="thead-dark">
        <tr>
            <th scope="col">Código</th>
            <th scope="col">Nome</th>
            <th scope="col">Laboratório </th>
            <th scope="col">Composição</th>
            <th scope="col">Tarja</th>
            <th scope="col">Tipo </th>
            <th scope="col">Código de Barras </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var medicamento in Model)
        {
            <tr>
                <th scope="row">@medicamento.Codigo</th>
                <td>@medicamento.Nome</td>
                <td>@medicamento.Laboratorio</td>
                <td>@medicamento.Composicao</td>
                <td>@medicamento.Tarja</td>
                <td> @medicamento.Tipo</td>
                <td> @medicamento.Produto_codigo_de_barras</td>

                <td style="width:80px">
                    <i>
                        @Html.ActionLink("", "Deletar", new { Numero = medicamento.Codigo }, new
                        {
                   @class = "bi bi-x-lg",
                            style = "color:red; font-size:x-large"
                        })
                    </i>

                    <i>
                        @Html.ActionLink("", "Update", new { Numero = medicamento.Codigo }, new
                        {
                  @class = "bi bi-pen",
                            style = "color:green; font-size:x-large"
                        })
                    </i>
                </td>
            </tr>
        }
    </tbody>
</table>

FarmaciaBD/Views/Medicamento/Inserir.cshtml
@model FarmaciaBD.Models.Medicamento
@{
    Layout = "_Layout";
}
@if (TempData["Exception"] != null) // para evitar mensagem de erro atoa
{
    <div class="alert alert-danger" role="alert">
        @TempData["Exception"]
    </div>
}
<br />
<br />
<h2 style="text-align: center">Cadastrar Novo Medicamento</h2>
<form method="post">
<input type="hidden" name="codigo" value="@Model.Codigo" />
<div class="row g-3">
    <div class="col-12">
        <label for="nome" class="form-label">Nome</label>
        <input type="text" name="nome" class="form-control" value="@Model.Nome" id="nome">
        <a style="color:red">
            @Html.ValidationMessage("nome")
        </a>
    </div>
    <div class="col-md-6">
        <label for="laboratorio" class="form-label">Laboratório</label>
        <input type="text" name="laboratorio" class="form-control" value="@Model.Laboratorio" id="laboratorio">

        <a style="color:red">
            @Html.ValidationMessage("laboratorio")
        </a>
    </div>
    <div class="col-md-6">
        <label for="composicao" class="form-label">Composição</label>
        <input type="text" name="composicao" class="form-control" value="@Model.Composicao" id="composicao">

        <a style="color:red">
            @Html.ValidationMessage("composicao")
        </a>
    </div>
    <div class="col-md-4">
        <label for="tarja" class="form-label">Tarja</label>
        <input type="text" name="tarja" class="form-control" value="@Model.Tarja" id="tarja">

        <a style="color:red">
            @Html.ValidationMessage("tarja")
        </a>
    </div>
    <div class="col-md-4">
        <label for="tipo" class="form-label">Tipo</label>
        <input type="text" name="tipo" class="form-control" value="@Model.Tipo" id="tipo">

        <a style="color:red">
            @Html.ValidationMessage("tipo")
        </a>
    </div>

    <div class="col-md-4">
        <label for="produto_codigo_de_barras" class="form-label">Código do Produto</label>
        <input type="text" name="produto_codigo_de_barras" class="form-control" value="@Model.Produto_codigo_de_barras" id="produto_codigo_de_barras">
        <a style="color:red">
            @Html.ValidationMessage("produto_codigo_de_barras")
        </a>
    </div>

</div>
<button type="submit" class="btn btn-secondary">Salvar</button>
    </form>
<!--TODO - retorno da pagina após o cadastro -->